import sqlite3

conn = sqlite3.connect("flashcards.db")
cursor = conn.cursor()

# Przykładowy zestaw i fiszki
set_name = "Top 100 Phrasal Verbs"

cursor.execute("INSERT INTO sets (name) VALUES (?)", (set_name,))

# Pobierz ID zestawu "Top 100 Business phrases"
cursor.execute("SELECT id FROM sets WHERE name = ?", (set_name,))
set_id = cursor.fetchone()[0]

flashcards = [
("poddawać się", "give up"),
("zdjąć", "take off"),
("opiekować się", "look after"),
("szukać", "look for"),
("nie móc się doczekać", "look forward to"),
("wstać", "get up"),
("kontynuować", "go on"),
("włączyć", "turn on"),
("wyłączyć", "turn off"),
("podnieść", "pick up"),
("odłożyć", "put down"),
("zabraknąć", "run out of"),
("założyć/ustawić", "set up"),
("zmyślić/pogodzić się", "make up"),
("zepsuć się/załamać się", "break down"),
("poruszyć temat/wychowywać", "bring up"),
("odwołać", "call off"),
("kontynuować", "carry on"),
("dowiedzieć się", "find out"),
("dogadywać się", "get along with"),
("wrócić", "get back"),
("dojść do siebie", "get over"),
("poddawać się", "give in"),
("wrócić", "go back"),
("dorastać", "grow up"),
("poczekać", "hold on"),
("kontynuować", "keep on"),
("zawieść", "let down"),
("zbadać", "look into"),
("uważać", "look out"),
("dostrzec/rozpoznać", "make out"),
("umrzeć", "pass away"),
("wybrać", "pick out"),
("odłożyć na później", "put off"),
("założyć (ubranie)", "put on"),
("spotkać/przypadkowo się natknąć", "run into"),
("wyczerpać", "run out"),
("pożegnać", "see off"),
("wyruszyć", "set off"),
("pomylić się", "slip up"),
("wstać", "stand up"),
("być podobnym", "take after"),
("wyjąć", "take out"),
("wyrzucić", "throw away"),
("przymierzyć", "try on"),
("pojawić się", "turn up"),
("odrzucić", "turn down"),
("uważać", "watch out"),
("ćwiczyć/rozwiązać", "work out"),
("zrywać/rozpadać się", "break up"),
("natknąć się", "come across"),
("wpaść na (pomysł)", "come up with"),
("odciąć", "cut off"),
("wypełnić", "fill in"),
("napełnić", "fill up"),
("wejść/wsiąść", "get in"),
("rozdać/ujawnić", "give away"),
("opóźnić/rabować", "hold up"),
("nadążać", "keep up"),
("sprawdzić", "look up"),
("zemdleć/rozdawać", "pass out"),
("zwrócić uwagę", "point out"),
("znosić", "put up with"),
("pojawić się", "show up"),
("zwolnić (tempo)", "slow down"),
("rozwiązać/posegregować", "sort out"),
("trzymać się", "stick to"),
("wyłączyć", "switch off"),
("włączyć", "switch on"),
("cofnąć/zwrócić", "take back"),
("przejąć", "take over"),
("podrzeć", "tear up"),
("przemyśleć", "think over"),
("wypróbować", "try out"),
("odwrócić", "turn around"),
("zużyć", "use up"),
("obudzić", "wake up"),
("rozgrzać", "warm up"),
("pracować nad", "work on"),
("zameldować się", "check in"),
("wymeldować się/sprawdzić", "check out"),
("podrzucić/spadać", "drop off"),
("przejrzeć/przejść przez", "go through"),
("spędzać czas", "hang out"),
("zwolnić (pracownika)", "lay off"),
("opłacać się", "pay off"),
("wskazać", "point at"),
("zjechać na bok", "pull over"),
("uciekać", "run away"),
("odłożyć", "set aside"),
("popisywać się", "show off"),
("wyróżniać się", "stand out"),
("zacząć (hobby)", "take up"),
("odwracać uwagę", "distract"),
("zatkać", "shut up"),
("udać się (powieść się)", "work out"),
("udać się (ktoś idzie)", "show up"),
("wymknąć się", "slip away"),
("przełączać", "switch over"),
("zgodzić się", "go along with"),
("kłócić się", "fall out"),
("zacząć", "set in"),
("odwiesić", "put down"),
("odrzucać", "brush off"),
("bić się", "pick on"),
("zrezygnować", "back out"),
("zawrócić", "turn back"),
("zawracać uwagę na", "focus on"),
("wejść (do budynku)", "come in"),
("wyjść (z budynku)", "go out"),
("przejąć kontrolę", "take charge"),
("wpaść na kogoś", "run across"),
("odpowiadać", "answer back"),
("zwrócić", "hand in"),
("wypić", "drink up"),
("posprzątać", "clean up"),
("odpocząć", "rest up"),
("zwrócić uwagę", "call attention to"),
]

cursor.executemany("INSERT INTO flashcards (word_pl, word_en, set_id) VALUES (?, ?, ?)", [(word_pl, word_en, set_id) for word_pl, word_en in flashcards])

conn.commit()
conn.close()

print("Baza danych została zaktualizowana i wypełniona przykładowymi danymi.")