import sqlite3

conn = sqlite3.connect("flashcards.db")
cursor = conn.cursor()

# Przykładowy zestaw i fiszki
set_name = "Top 200 business sentences"

cursor.execute("INSERT INTO sets (name) VALUES (?)", (set_name,))

# Pobierz ID zestawu "Top 100 Business phrases"
cursor.execute("SELECT id FROM sets WHERE name = ?", (set_name,))
set_id = cursor.fetchone()[0]

flashcards = [
("Zacznijmy spotkanie", "Let's start the meeting"),
("Czy wszyscy są gotowi?", "Is everyone ready?"),
("Proszę, przejdźmy do kolejnego punktu", "Let's move on to the next item"),
("Przejdźmy do agendy", "Let's proceed to the agenda"),
("Mam coś do omówienia", "I have something to discuss"),
("Potrzebujemy omówić ten temat", "We need to discuss this topic"),
("Dodajmy to do agendy", "Let's add it to the agenda"),
("Czy ktoś jeszcze coś doda?", "Does anyone have anything to add?"),
("Zanotuję twoje uwagi", "I'll note down your comments"),
("Czy jest coś do podsumowania?", "Is there anything to summarize?"),
("Przejdźmy do raportu statusu", "Let's move on to the status report"),
("Mamy 10 minut", "We have 10 minutes"),
("Spotkanie się przedłuża", "The meeting is running over time"),
("Chodźmy na przerwę", "Let's take a break"),
("Czy wszyscy się zgadzają?", "Does everyone agree?"),
("Kto chce zgłosić uwagi?", "Who wants to share feedback?"),
("Przepraszam, uruchomię kamerę", "Sorry, I'll turn on the camera"),
("Przepraszam za zakłócenia", "Sorry for the interruption"),
("Spotykamy się jutro o...?", "Are we meeting tomorrow at...?"),
("Dziękuję wszystkim za dzisiaj", "Thank you all for today"),
("Co słychać?", "What's up?"),
("Jak leci?", "How's it going?"),
("Miło cię widzieć", "Nice to see you"),
("Było miło wczoraj", "It was nice yesterday"),
("Co u ciebie nowego?", "What's new with you?"),
("Jak tam weekend?", "How was the weekend?"),
("Masz plany na weekend?", "Any plans for the weekend?"),
("Jak minął dzień?", "How did your day go?"),
("Fajnie cię znowu zobaczyć", "Great to see you again"),
("Dobrze wyglądasz dzisiaj", "You look good today"),
("Zacznijmy od krótkiej pogawędki", "Let's start with a quick chat"),
("Jak tam pogoda u ciebie?", "How's the weather on your side?"),
("Wygląda na to, że dużo pracujesz", "Looks like you're working a lot"),
("Byłeś już na tym webinarze?", "Have you already attended that webinar?"),
("Widzę, że masz nową kawę", "I see you have a new coffee"),
("Zmiany działają sprawnie", "Things are working smoothly"),
("Potrzebuję kawy, co u ciebie?", "I need coffee, what about you?"),
("Dobrze odpocząłem po pracy", "I had a good rest after work"),
("Zjadłeś coś dzisiaj?", "Did you eat anything today?"),
("Masz jakieś weekendowe plany?", "Do you have any weekend plans?"),
("Mam problem z kompilacją", "I'm having trouble with the compilation"),
("Czy możesz spojrzeć na mój kod?", "Can you take a look at my code?"),
("Kod działa na moim komputerze, ale nie na serwerze", "The code works on my machine but not on the server"),
("Musimy zoptymalizować tę funkcję", "We need to optimize this function"),
("Czy przetestowałeś ostatnią wersję?", "Did you test the latest version?"),
("Zaktualizujmy dokumentację", "Let's update the documentation"),
("Nasz system nie odpowiada", "Our system is not responding"),
("Sprawdź logi serwera", "Check the server logs"),
("Stworzyłem zgłoszenie w JIRA dla tego zadania", "I created a JIRA issue for this task"),
("Musimy wdrożyć poprawkę", "We need to deploy a fix"),
("Zróbmy code review", "Let's do a code review"),
("Potrzebuję linka do repozytorium", "I need the link to the repository"),
("Przypiszmy user story", "Let's assign the user story"),
("Jaki jest zakres tego projektu?", "What is the scope of this project?"),
("Wdrożenie wymaga testów integracyjnych", "The deployment requires integration tests"),
("Miałeś merge conflicts?", "Did you have merge conflicts?"),
("Sprawdzę to u siebie na maszynie", "I'll check it on my machine"),
("Zaloguję się do środowiska testowego", "I'll log into the test environment"),
("Jestem gotowy do demo", "I am ready for the demo"),
("Potrzebujemy szybkiego prototypu", "We need a quick prototype"),
("Poproszę o przegląd kodu", "Could you please review the code?"),
("Jeżeli potrzebujesz pomocy, daj znać", "If you need help, let me know"),
("Zróbmy spotkanie ad hoc", "Let's have an ad-hoc meeting"),
("Podzielimy się zadaniami", "Let's split the tasks"),
("Kto jest odpowiedzialny za to zadanie?", "Who is responsible for this task?"),
("Pracujemy zespołowo", "We work as a team"),
("Dziękuję za wsparcie", "Thank you for the support"),
("Nie mogę się doczekać współpracy", "I look forward to working with you"),
("Przydziel zadanie", "Assign the task"),
("Czy możesz to przetestować?", "Can you test this?"),
("Podzielę się dokumentem na dysku", "I'll share the document on the drive"),
("Współpraca międzyzespołowa jest kluczowa", "Cross-team collaboration is crucial"),
("Czy możemy zrobić burzę mózgów?", "Can we have a brainstorming session?"),
("Proszę o feedback do końca tygodnia", "Please give feedback by the end of the week"),
("Poinformuję zespół o zmianach", "I'll inform the team about the changes"),
("Przejrzę to później", "I'll review it later"),
("Przesyłam projekt mailowo", "I'll send the project via email"),
("Pracujemy nad tym razem", "We are working on this together"),
("Dodaj mnie do kanału Slack", "Add me to the Slack channel"),
("Udostępniłem dokumenty w Google Drive", "I shared the documents in Google Drive"),
("Dziękuję za uwagę", "Thank you for your attention"),
("Proszę spojrzeć na ten wykres", "Please look at this chart"),
("Jak widzicie na slajdzie", "As you can see on the slide"),
("Chciałbym przedstawić wyniki", "I would like to present the results"),
("Powtarzam punkt", "Let me repeat the point"),
("Przejdźmy do następnego slajdu", "Let's move to the next slide"),
("Podsumowując najważniejsze wnioski", "To summarize the key findings"),
("Czas na pytania", "Time for questions"),
("W razie pytań proszę pytać", "If you have questions, please ask"),
("Starałem się być krótki", "I tried to be brief"),
("To wszystko z mojej strony", "That's all from me"),
("Dziękuję za współpracę", "Thank you for your cooperation"),
("Prezentacja została nagrana", "The presentation has been recorded"),
("To jest wprowadzenie/tytuł slajdu", "This is the introduction/title of the slide"),
("Uczestnicy mogą zabrać głos", "Participants can speak up"),
("Proszę wyciszyć mikrofon", "Please mute your microphone"),
("Przygotowałem agendę prezentacji", "I prepared the presentation agenda"),
("Czy wszyscy widzą mój ekran?", "Can everyone see my screen?"),
("Nagrywam to spotkanie", "I'm recording this meeting"),
("Potrzebujemy jeszcze jednej informacji", "We need one more piece of information"),
("Szanowni Państwo", "Dear all"),
("Z poważaniem", "Best regards"),
("Dziękuję za odpowiedź", "Thank you for your reply"),
("Na wstępie chciałbym podziękować", "Firstly, I would like to thank you"),
("Załączam dokument", "I attach the document"),
("W razie pytań służę pomocą", "If you have any questions, I'm here to help"),
("Proszę o potwierdzenie otrzymania", "Please confirm receipt"),
("Przepraszam za opóźnienie w odpowiedzi", "Sorry for the delay in responding"),
("Na marginesie...", "By the way..."),
("Przesyłam moje uwagi", "I'm sending my comments"),
("Poniżej znajdą Państwo szczegóły", "Below you will find the details"),
("Potwierdzam spotkanie na jutro", "I confirm the meeting for tomorrow"),
("Czy moglibyśmy przełożyć termin?", "Could we reschedule?"),
("Proszę o szybką odpowiedź", "Please respond quickly"),
("Załączony plik zawiera...", "The attached file contains..."),
("Dziękuję za szybką reakcję", "Thank you for the prompt response"),
("Pragnę poinformować, że...", "I would like to inform that..."),
("W razie potrzeby służę dodatkowymi informacjami", "If needed, I'm available for further information"),
("Z góry dziękuję za pomoc", "Thank you in advance for your help"),
("Pozdrawiam serdecznie", "Kind regards"),
("Robimy planowanie sprintu", "We are doing sprint planning"),
("Proponuję programowanie parami", "I suggest pair programming"),
("Zrozumiałem, wezmę się za to", "Got it, I'll take care of it"),
("Przypiszcie mi, proszę, to zadanie", "Please assign the task to me"),
("Napiszę testy jednostkowe", "I will write unit tests"),
("Sprawdzę to na stagingu", "I will check it on staging"),
("Kiedy jest deploy na produkcję?", "When is the deploy to production?"),
("Musimy to eskalować", "We need to escalate this"),
("Utworzę zgłoszenie w JIRA", "I will create a ticket in JIRA"),
("Czy ktoś zna rozwiązanie?", "Does anyone know the solution?"),
("Kod ma błąd", "The code has a bug"),
("Mamy awarię na produkcji", "We have an outage in production"),
("Zareagujmy szybko", "Let's react quickly"),
("Wrócę do tego tematu później", "I'll get back to this topic later"),
("Wysłałem pull request", "I sent a pull request"),
("Dodam to do backlogu", "I'll add this to the backlog"),
("Zgłoszenie jest priorytetowe", "This ticket is high priority"),
("Testy jednostkowe zaliczone", "Unit tests passed"),
("Logi nic nie pokazują", "The logs show nothing"),
("Daj mi znać, jak skończysz", "Let me know when you finish"),
("Spotkamy się w środę o 10?", "Shall we meet on Wednesday at 10?"),
("Czy możemy ustalić deadline?", "Can we set a deadline?"),
("Potrzebuję dostępu do serwera", "I need access to the server"),
("Mam pomysł na rozwiązanie", "I have an idea for a solution"),
("Mam pytanie dotyczące projektu", "I have a question regarding the project"),
("Nie rozumiem, czy możesz powtórzyć?", "I don't understand, could you repeat that?"),
("Chętnie ci pomogę", "I'll be happy to help you"),
("Przejdźmy do szczegółów", "Let's move to the details"),
("Aktualizuję status w systemie", "I'm updating the status in the system"),
("Proszę o codzienny stand-up", "Please hold daily stand-ups"),
("Przygotowuję backlog refinement", "I'm preparing the backlog refinement"),
("Czy mogę zobaczyć Twój kod?", "Can I see your code?"),
("Bądź punktualnie, proszę", "Be punctual, please"),
("Trzymajmy się harmonogramu", "Let's stick to the schedule"),
("Pracujemy nad MVP", "We are working on the MVP"),
("Ustalimy kolejne kroki", "We'll determine the next steps"),
("Jakie są blokery tego zadania?", "What are the blockers for this task?"),
("Ustalam priorytety", "I set the priorities"),
("Kończę teraz to zadanie", "I'm finishing this task now"),
("Potrzebuję szacunków", "I need estimates"),
("Określimy wymagania", "Let's define the requirements"),
("Trzeba napisać wymagania techniczne", "Technical requirements need to be written"),
("Zbieramy feedback od klienta", "We are gathering feedback from the client"),
("To wprowadzimy w kolejnym wydaniu", "We'll include it in the next release"),
("Czas na retrospektywę", "Time for the retrospective"),
("Implementacja idzie zgodnie z planem", "Implementation is on schedule"),
("Przekaż swoje uwagi do dokumentu", "Add your comments to the document"),
("Następne spotkanie będzie w czwartek", "Next meeting will be on Thursday"),
("Zaproponuję zmiany w pull requeście", "I will propose changes in the pull request"),
("Komunikacja między zespołami jest kluczowa", "Communication between teams is crucial"),
("Dziękuję za update", "Thanks for the update"),
("Następne zadanie wezmę ja", "I will take the next task"),
("Czy mogę coś wyjaśnić?", "Can I clarify something?"),
("Kontaktuję się z klientem w sprawie...", "I'm contacting the client about..."),
("Wysłaliśmy maila do zespołu X", "We have sent an email to team X"),
("Dodam nowy branch", "I'll add a new branch"),
("Backlog refinement jest jutro", "Backlog refinement is tomorrow"),
("Zawiesiłem bazę danych", "I put the database into maintenance mode"),
("Przetestuję to", "I will test it"),
("Zgłaszam to w Jira", "I'm reporting this to Jira"),
("Potrzebuję licencji", "I need a license"),
("Mój kolega pomoże w code review", "My colleague will help with code review"),
("Architektura mikroserwisów", "Microservices architecture"),
("Mamy zadania do przeniesienia do sprintu", "We have tasks to move to the sprint"),
("Zróbmy synchronizację", "Let's sync up"),
("Będzie rebase kodu", "There will be a code rebase"),
("Kod wymaga refaktoryzacji", "The code needs refactoring"),
("Dodam testy", "I'll add tests"),
("Zakończymy ten etap", "We will finish this phase"),
("To był dobry sprint", "It was a good sprint"),
("Nowy sprint zaczynamy jutro", "We'll start a new sprint tomorrow"),
("Zarządzanie projektem jest ważne", "Project management is important"),
("Mam problemy z wydajnością", "I'm having performance issues"),
("Proszę o szczery feedback", "I would like honest feedback"),
("Czy mogę zaoferować pomoc?", "Can I offer some help?"),
("Stworzyłem kanał na Slacku", "I created a Slack channel"),
("Spotkajmy się pod koniec dnia", "Let's meet at the end of the day"),
("Wyślę przypomnienie mailowe", "I'll send a reminder email"),
("Zamykamy to zadanie", "Let's close this task"),
("Mam nadzieję, że to pomoże", "I hope this helps"),
("Przygotujmy spotkanie z zespołem", "Let's schedule a meeting with the team"),
("Proszę znaleźć w załączniku raport", "Please find the report attached"),
("Potwierdź proszę odbiór tej wiadomości", "Please confirm receipt of this email"),
("Czy możesz zaktualizować harmonogram projektu?", "Can you update the project timeline?"),
("Potrzebujemy omówić priorytety", "We need to discuss priorities"),
("Kiedy masz czas na krótką rozmowę?", "When do you have time for a quick call?"),
("Prześlij mi agendę przed spotkaniem", "Send me the agenda before the meeting"),
("Czy możemy przesunąć termin?", "Can we reschedule the deadline?"),
("Dziękuję za szybką odpowiedź", "Thank you for the prompt response"),
("Przepraszam za opóźnienie", "I apologize for the delay"),

("Proszę udostępnij dokumenty", "Please share the documents"),
("Potrzebuję dostępu do systemu", "I need access to the system"),
("Zaktualizowałem prezentację", "I have updated the presentation"),
("Czy możesz sprawdzić dane?", "Can you verify the data?"),
("Prześlij mi proszę szczegóły", "Please send me the details"),
("Potrzebujemy zatwierdzenia budżetu", "We need budget approval"),
("Jaki jest status projektu?", "What is the status of the project?"),
("Czy otrzymałeś moją poprzednią wiadomość?", "Did you receive my previous email?"),
("Proszę przygotuj krótki raport", "Please prepare a brief report"),
("Spotkajmy się na Zoomie", "Let's meet on Zoom"),

("Prześlij link do spotkania", "Send the meeting link"),
("Potrzebujemy zatwierdzić kontrakt", "We need to approve the contract"),
("Proszę o potwierdzenie udziału", "Please confirm your participation"),
("Czy możesz zorganizować wideokonferencję?", "Can you set up a video conference?"),
("Publikacja raportu nastąpi jutro", "The report will be published tomorrow"),
("Kto jest odpowiedzialny za to zadanie?", "Who is responsible for this task?"),
("Proszę przypomnij mi o tym", "Please remind me about this"),
("Potrzebujemy kolejnego spotkania", "We need a follow-up meeting"),
("Zaktualizuj mnie na bieżąco", "Keep me updated"),
("Zamknijmy ten punkt agendy", "Let's close this agenda item"),

("Czy wszyscy zabrali głos?", "Has everyone had a chance to speak?"),
("Czy mogę prosić o feedback?", "May I ask for feedback?"),
("Dziękuję za twoje zaangażowanie", "Thank you for your involvement"),
("Proszę wyjaśnij to dokładniej", "Please clarify that further"),
("Zatwierdziłem dokumenty", "I have approved the documents"),
("Potrzebujemy zwiększyć zasoby", "We need to increase resources"),
("Jaka jest prognoza na przyszły kwartał?", "What is the forecast for next quarter?"),
("Przypomnij uczestnikom o spotkaniu", "Remind participants about the meeting"),
("Czy możesz przygotować prezentację?", "Can you prepare the presentation?"),
("Proszę zweryfikuj koszty", "Please verify the costs"),

("Ustalmy cele na ten tydzień", "Let's set goals for this week"),
("Potrzebuję zatwierdzenia od klienta", "I need client approval"),
("Kto przegląda ten dokument?", "Who is reviewing this document?"),
("Proszę dodaj to do listy zadań", "Please add this to the task list"),
("Czy wszystko jest jasne?", "Is everything clear?"),
("Spotkanie zaczyna się za dziesięć minut", "The meeting starts in ten minutes"),
("Zamknij plik po zakończeniu", "Close the file when you finish"),
("Czy możesz zorganizować lunch?", "Can you arrange lunch?"),
("Potrzebujemy harmonogramu wdrożenia", "We need an implementation schedule"),
("Prześlij notatki ze spotkania", "Send the meeting minutes"),

("Czy możesz to wyjaśnić?", "Can you explain this?"),
("Proszę ogranicz się do pięciu slajdów", "Please limit it to five slides"),
("Jaki jest budżet projektu?", "What is the project budget?"),
("Potwierdź termin dostawy", "Confirm the delivery date"),
("Czy potrzebujesz pomocy?", "Do you need assistance?"),
("Proszę wyślij fakturę", "Please send the invoice"),
("Zamknij proszę przeglądarkę", "Please close the browser"),
("Przypisz zadania zespołowi", "Assign tasks to the team"),
("Potrzebujemy zebrania budżetowego", "We need a budget meeting"),
("Kiedy możemy omówić to ponownie?", "When can we discuss this again?"),

("Proszę potwierdź adres e-mail", "Please confirm the email address"),
("Czy to jest priorytet?", "Is this a priority?"),
("Zaktualizuj formularz", "Update the form"),
("Proszę dołącz wyniki analizy", "Please include the analysis results"),
("Potrzebuję natychmiastowej odpowiedzi", "I need an immediate response"),
("Czy możesz przygotować kosztorys?", "Can you prepare a cost estimate?"),
("Prześlij mi wyniki badań", "Send me the research findings"),
("Użyj szablonu firmowego", "Use the corporate template"),
("Przypilnuj, proszę, terminu", "Please ensure the deadline is met"),
("Zorganizuj szkolenie dla zespołu", "Organize training for the team"),

("Czy zgadza się to z twoją wiedzą?", "Does this align with your understanding?"),
("Proszę wprowadź poprawki", "Please make the corrections"),
("Potwierdziłem obecność wszystkich", "I have confirmed everyone's attendance"),
("Czy ktoś ma pytania?", "Does anyone have questions?"),
("Prześlij plan działania", "Send the action plan"),
("Czy możemy to przetestować?", "Can we test this?"),
("Proszę potwierdź dostępność", "Please confirm availability"),
("Jaki jest czas realizacji?", "What is the lead time?"),
("Zgodziłem się na warunki", "I agreed to the terms"),
("Proszę przypomnij mi w przyszłym tygodniu", "Please remind me next week"),

("Czy jest jakiś feedback od klienta?", "Is there any feedback from the client?"),
("Potrzebujemy zaktualizować politykę", "We need to update the policy"),
("Proszę podsumuj spotkanie", "Please summarize the meeting"),
("Skonsultuj się z prawnikiem", "Consult with the legal department"),
("Czy możemy przyspieszyć ten proces?", "Can we expedite this process?"),
("Proszę podać kluczowe wskaźniki", "Please provide the key metrics"),
("Zaproponuj rozwiązanie", "Propose a solution"),
("Potwierdzam zakończenie zadania", "I confirm the task is completed"),
("Utwórz kopię zapasową danych", "Create a data backup"),
("Prześlij odpowiednie zaświadczenia", "Send the relevant documentation"),

("Czy możemy zrobić przerwę?", "Can we take a break?"),
("Proszę przypilnuj agendy", "Please keep track of the agenda"),
("Potrzebujemy omówić ryzyko", "We need to discuss risks"),
("Zaprojektuj nowy wykres", "Design a new chart"),
("Czy ten raport jest skończony?", "Is this report finished?"),
("Prześlij informacje zwrotne", "Send your feedback"),
("Proszę przygotuj kopię kontraktu", "Please prepare a copy of the contract"),
("Zaktualizuj status w systemie", "Update the status in the system"),
("Potwierdzam otrzymanie dokumentów", "I confirm receipt of the documents"),
("Czy wszystko idzie zgodnie z planem?", "Is everything going according to plan?"),

]

cursor.executemany("INSERT INTO flashcards (word_pl, word_en, set_id) VALUES (?, ?, ?)", [(word_pl, word_en, set_id) for word_pl, word_en in flashcards])

conn.commit()
conn.close()

print("Baza danych została zaktualizowana i wypełniona przykładowymi danymi.")