import sqlite3

conn = sqlite3.connect("flashcards.db")
cursor = conn.cursor()

# Przykładowy zestaw i fiszki
set_name = "Top 500 words and phrases"

cursor.execute("INSERT INTO sets (name) VALUES (?)", (set_name,))

# Pobierz ID zestawu "Top 100 Business phrases"
cursor.execute("SELECT id FROM sets WHERE name = ?", (set_name,))
set_id = cursor.fetchone()[0]

flashcards = [
("cześć", "hello"),
("do widzenia", "goodbye"),
("dziękuję", "thank you"),
("proszę", "please"),
("przepraszam", "sorry"),
("jak się masz", "how are you"),
("miło mi cię poznać", "nice to meet you"),
("co u ciebie słychać", "what's up"),
("dobry wieczór", "good evening"),
("dobranoc", "good night"),
("co robisz", "what are you doing"),
("skręć w lewo", "turn left"),
("skręć w prawo", "turn right"),
("idz prosto", "go straight"),
("skręć w drugą przecznicę", "take the second turning"),
("skręć w następną ulicę w prawo", "take the next street on the right"),
("skręć w następną ulicę w lewo", "take the next street on the left"),
("skrzyżowanie", "intersection"),
("przystanek autobusowy", "bus stop"),
("stacja kolejowa", "train station"),
("metro", "subway"),
("lotnisko", "airport"),
("odlot", "departure"),
("przylot", "arrival"),
("odprawa bagażowa", "baggage check-in"),
("odbiór bagażu", "baggage claim"),
("wypożyczalnia samochodów", "car rental"),
("hotel", "hotel"),
("recepcja", "reception"),
("klucz do pokoju", "room key"),
("klucz", "key"),
("zwiedzać muzeum", "visit a museum"),
("wystawa", "exhibition"),
("płatność", "payment"),
("wstać z łóżka", "get out of bed"),
("umówić się na spotkanie", "schedule a meeting"),
("odwołać spotkanie", "cancel a meeting"),
("uczę się angielskiego", "I'm learning English"),
("mam ochotę na kawę", "I feel like having coffee"),
("gotować obiad", "cook dinner"),
("sprzątać pokój", "clean the room"),
("robić zakupy", "do the shopping"),
("oglądać telewizję", "watch TV"),
("czytać książkę", "read a book"),
("spać", "sleep"),
("wstawać rano", "get up in the morning"),
("zasypiać", "fall asleep"),
("brać prysznic", "take a shower"),
("myć zęby", "brush your teeth"),
("iść do pracy", "go to work"),
("wracać z pracy", "come back from work"),
("zjeść śniadanie", "have breakfast"),
("zjeść obiad", "have lunch"),
("zrobić przerwę", "take a break"),
("napisać e-mail", "write an email"),
("wysłać e-mail", "send an email"),
("przeczytać e-mail", "read an email"),
("temat wiadomości", "email subject"),
("z poważaniem", "yours sincerely"),
("proszę o odpowiedź", "please reply"),
("załącznik", "attachment"),
("dołączony plik", "attached file"),
("adres e-mail", "email address"),
("spotkanie biznesowe", "business meeting"),
("prezentacja", "presentation"),
("raport", "report"),
("projekt", "project"),
("pracownik", "employee"),
("pracodawca", "employer"),
("umowa", "contract"),
("podpisać umowę", "sign a contract"),
("przełożony", "supervisor"),
("kolega z pracy", "colleague"),
("zadzwonić do klienta", "call a client"),
("zostać na spotkaniu", "attend the meeting"),
("prowadzić spotkanie", "lead a meeting"),
("zamknąć projekt", "close a project"),
("opóźnić projekt", "delay the project"),
("konferencja", "conference"),
("przemówienie", "speech"),
("umówić rozmowę", "arrange a call"),
("umówić spotkanie", "set up a meeting"),
("przeprowadzić prezentację", "conduct a presentation"),
("zeskanować dokumenty", "scan documents"),
("wydrukować", "print"),
("drukarka", "printer"),
("skaner", "scanner"),
("komputer", "computer"),
("klawiatura", "keyboard"),
("myszka", "mouse"),
("monitor", "monitor"),
("ładowarka do laptopa", "laptop charger"),
("oprogramowanie", "software"),
("drukować", "print"),
("odbierać telefon", "answer the phone"),
("ustawić powiadomienie", "set a reminder"),
("włączyć komputer", "turn on the computer"),
("wyłączyć komputer", "shut down the computer"),
("zarezerwować lot", "book a flight"),
("zarezerwować pokój", "book a room"),
("wynająć samochód", "rent a car"),
("spakować walizki", "pack your bags"),
("półka nad głową", "overhead bin"),
("bilet powrotny", "round-trip ticket"),
("bilet w jedną stronę", "one-way ticket"),
("bilet jednodniowy", "day ticket"),
("przystanek", "stop"),
("przesiadka", "transfer"),
("karta pokładowa", "boarding pass"),
("kontrola bezpieczeństwa", "security check"),
("przejście na pokład", "boarding gate"),
("terminal lotniska", "airport terminal"),
("transport publiczny", "public transport"),
("powrót", "return"),
("przejażdżka", "ride"),
("zarezerwować pobyt", "book a stay"),
("plan podróży", "itinerary"),
("odpoczynek", "rest"),
("podróż służbowa", "business trip"),
("przewodnik", "tour guide"),
("mapa", "map"),
("źle się czuć w samolocie", "feel sick on a plane"),
("opóźniony lot", "delayed flight"),
("późniejszy lot", "later flight"),
("wcześniejszy lot", "earlier flight"),
("gdybym mógł...", "if I could..."),
("w drodze powrotnej", "on the way back"),
("zamknąć bagaż", "close the luggage"),
("zwiedzić stolicę", "visit the capital"),
("krótka wycieczka", "short trip"),
("długi lot", "long flight"),
("długi odpoczynek", "long rest"),
("plan lotów", "flight schedule"),
("plan jazdy", "timetable"),
("zrobić zakupy w sklepie spożywczym", "do grocery shopping"),
("obrane ziemniaki", "peeled potatoes"),
("kawa z mlekiem", "coffee with milk"),
("pić kawę", "drink coffee"),
("jeść lunch", "have lunch"),
("mięso", "meat"),
("warzywa", "vegetables"),
("owoce", "fruit"),
("piec", "bake"),
("smażyć", "fry"),
("gotować", "boil"),
("sos", "sauce"),
("zupa", "soup"),
("sałatka", "salad"),
("do picia", "drink"),
("przekąska", "snack"),
("śniadanie na mieście", "breakfast out"),
("pójść na kolację", "go out for dinner"),
("zjeść na mieście", "eat out"),
("płacić rachunek", "pay the bill"),
("zapłacić rachunek", "pay the bill"),
("zapłacić gotówką", "pay cash"),
("zapłacić kartą", "pay by card"),
("danie dnia", "dish of the day"),
("szef kuchni", "chef"),
("karta dań", "menu"),
("trafić na wyprzedaż", "find a sale"),
("sklep odzieżowy", "clothing store"),
("centrum handlowe", "shopping center"),
("przymierzać ubrania", "try on clothes"),
("rozmiar", "size"),
("przymierzalnia", "fitting room"),
("kupować", "buy"),
("w sklepie", "in the store"),
("paragon", "receipt"),
("rabat", "discount"),
("cena", "price"),
("drogi", "expensive"),
("tani", "cheap"),
("promocja", "promotion"),
("zamawiać online", "order online"),
("dostawa", "delivery"),
("koszyk zakupowy", "shopping cart"),
("dodać do koszyka", "add to cart"),
("polityka zwrotów", "return policy"),
("wymienić", "exchange"),
("zwrot", "return (of goods)"),
("złoty", "zloty"),
("autobus", "bus"),
("pociąg", "train"),
("ruch uliczny", "traffic"),
("korki uliczne", "traffic jams"),
("jazda samochodem", "driving"),
("prowadzić samochód", "drive a car"),
("wysiadać", "get off"),
("wsiadać", "get on"),
("pasażer", "passenger"),
("rodzice", "parents"),
("siostra", "sister"),
("brat", "brother"),
("mąż", "husband"),
("żona", "wife"),
("dziecko", "child"),
("dzieci", "children"),
("syn", "son"),
("córka", "daughter"),
("dziadek", "grandfather"),
("babcia", "grandmother"),
("wnuczek", "grandson"),
("wnuczka", "granddaughter"),
("siostrzeniec", "nephew"),
("bratanek", "nephew"),
("bratowa", "sister-in-law"),
("teść", "father-in-law"),
("teściowa", "mother-in-law"),
("kuzyn", "cousin (male)"),
("kuzynka", "cousin (female)"),
("przyjaciel", "friend"),
("przyjaciółka", "friend (female)"),
("znajomy", "acquaintance"),
("znajoma", "acquaintance (female)"),
("polecenie", "recommendation"),
("umowa na czas określony", "fixed-term contract"),
("umowa na czas nieokreślony", "open-ended contract"),
("godziny pracy", "working hours"),
("nadzorować", "supervise"),
("delegacja", "business trip"),
("mieć dyżur", "be on duty"),
("urlop macierzyński", "maternity leave"),
("urlop tacierzyński", "paternity leave"),
("zwolnienie lekarskie", "sick leave"),
("etat", "full-time position"),
("umowa o dzieło", "contract for a specific task"),
("umowa zlecenie", "task-specific contract"),
("świadczenia socjalne", "social benefits"),
("ból głowy", "headache"),
("ból brzucha", "stomach ache"),
("ból pleców", "back pain"),
("ból zęba", "toothache"),
("kaszel", "cough"),
("gorączka", "fever"),
("lekarz", "doctor"),
("szpital", "hospital"),
("leczenie", "treatment"),
("oddział szpitalny", "hospital ward"),
("pogotowie", "emergency services"),
("straż pożarna", "fire brigade"),
("policja", "police"),
("apteka", "pharmacy"),
("recepta", "prescription"),
("dolegliwości", "ailments"),
("przeciwwskazania", "contraindications"),
("uczyć się", "learn"),
("nauczyciel", "teacher"),
("szkoła", "school"),
("klasa", "class"),
("lekcja", "lesson"),
("studia", "studies"),
("uczelnia", "university"),
("egzamin", "exam"),
("egzamin poprawkowy", "resit exam"),
("zdać egzamin", "pass an exam"),
("oblać egzamin", "fail an exam"),
("ocena", "grade"),
("dostać piątkę", "get an A (school grade)"),
("dostać jedynkę", "get an F (school grade)"),
("wykłady", "lectures"),
("ćwiczenia", "tutorials"),
("seminarium", "seminar"),
("biblioteka", "library"),
("książka", "book"),
("pisemnie", "in writing"),
("robić prezentację", "make a presentation"),
("przygotować prezentację", "prepare a presentation"),
("prezentować wyniki", "present results"),
("wyznaczyć zadania", "assign tasks"),
("zadać pytanie", "ask a question"),
("uzyskać odpowiedź", "get an answer"),
("pisać raport", "write a report"),
("analizować dane", "analyze data"),
("rozwijać projekt", "develop a project"),
("spotkanie zespołu", "team meeting"),
("spotkanie indywidualne", "one-on-one meeting"),
("spotkanie grupowe", "group meeting"),
("zrobić krótką przerwę", "take a short break"),
("przerwa obiadowa", "lunch break"),
("przerwa kawowa", "coffee break"),
("rozpocząć spotkanie", "start the meeting"),
("zakończyć spotkanie", "end the meeting"),
("mieć spotkanie online", "have an online meeting"),
("spotkanie face-to-face", "face-to-face meeting"),
("wziąć urlop", "take a vacation"),
("relaksować się", "relax"),
("uprawiać sport", "exercise"),
("biegać codziennie", "run every day"),
("iść na spacer", "go for a walk"),
("iść na jogging", "go jogging"),
("robić przerwę od pracy", "take a break from work"),
("wyjść na miasto", "go out (on town)"),
("spotkać się z przyjacielem", "meet a friend"),
("pójść na koncert", "go to a concert"),
("obejrzeć film", "watch a movie"),
("zasnąć przed telewizorem", "fall asleep in front of the TV"),
("telefon służbowy", "business phone"),
("telefon komórkowy", "mobile phone"),
("rozmowa telefoniczna", "phone call"),
("dzwonić do kogoś", "call someone"),
("rozłączyć się przypadkowo", "hang up accidentally"),
("odbierać telefon", "answer the phone"),
("odebrać telefon", "pick up the phone"),
("telefon jest zajęty", "the line is busy"),
("zostawić wiadomość", "leave a message"),
("prześlij wiadomość", "send a message"),
("sms", "text message"),
("wiadomość głosowa", "voicemail"),
("rozpocząć rozmowę", "start a conversation"),
("przerwać rozmowę", "break off a conversation"),
("jutro", "tomorrow"),
("w przyszłym tygodniu", "next week"),
("w zeszłym tygodniu", "last week"),
("za godzinę", "in an hour"),
("za pół godziny", "in half an hour"),
("za chwilę", "in a moment"),
("zaraz", "soon"),
("teraz", "now"),
("ostatnio", "lately"),
("więcej", "more"),
("mniej", "less"),
("od razu", "right away"),
("wkrótce", "soon"),
("za chwilkę", "in a moment"),
("już", "already"),
("jeszcze", "still/yet"),
("szczęśliwy", "happy"),
("smutny", "sad"),
("zły", "angry"),
("wzruszony", "moved"),
("zadowolony", "satisfied"),
("zaskoczony", "surprised"),
("dziwić się", "be surprised"),
("nierozumiejący", "confused"),
("przygnębiony", "upset"),
("zmęczony", "tired"),
("wypoczęty", "relaxed"),
("podekscytowany", "excited"),
("rozczarowany", "disappointed"),
("czasami", "sometimes"),
("zawsze", "always"),
("nigdy", "never"),
("codziennie", "every day"),
("rzadko", "rarely"),
("dobry", "good"),
("łatwy", "easy"),
("trudny", "difficult"),
("szybki", "fast"),
("wolny", "slow"),
("piękny", "beautiful"),
("brzydki", "ugly"),
("młody", "young"),
("old", "stary"),
("krótki", "short"),
("wysoki", "tall/high"),
("niski", "short (in height)/low"),
("ciężki", "heavy"),
("lekki", "light (weight)"),
("gorący", "hot"),
("zimny", "cold"),
("świeży", "fresh"),
("głośny", "loud"),
("cichy", "quiet"),
("częsty", "frequent"),
("rzadki", "rare"),
("wysoki", "high"),
("niski", "low"),
("grać w piłkę nożną", "play football"),
("jak się masz", "how are you"),
("dzień dobry", "good morning"),
("proszę powtórzyć", "could you repeat that"),
("powiedz to jeszcze raz", "say it again"),
("ile to kosztuje", "how much is it"),
("gdzie jest", "where is"),
("toaleta", "restroom"),
("łazienka", "bathroom"),
("toaleta jest zamknięta", "restroom is closed"),
("gdzie jest bankomat", "where is the ATM"),
("czy to wolne", "is this seat taken"),
("wiosna", "spring"),
("lato", "summer"),
("jesień", "autumn"),
("zima", "winter"),
("parking", "parking lot"),
("tramwaj", "tram"),
("sklep spożywczy", "grocery store"),
("kino", "cinema"),
("bilet autobusowy", "bus ticket"),
("przykro mi", "I'm sorry"),
("na razie", "see you"),
("co tam", "what's up"),
("przejść do sedna", "get down to business"),
("trzymam kciuki", "I'm keeping my fingers crossed"),
("poczekać chwilę", "wait a moment"),
("przede wszystkim", "above all"),
("randka", "date (romantic date)"),
("zakochać się", "fall in love"),
("rozstać się", "break up"),
("świat", "world"),
("internet", "internet"),
("zaliczyć egzamin", "pass an exam"),
]

cursor.executemany("INSERT INTO flashcards (word_pl, word_en, set_id) VALUES (?, ?, ?)", [(word_pl, word_en, set_id) for word_pl, word_en in flashcards])

conn.commit()
conn.close()

print("Baza danych została zaktualizowana i wypełniona przykładowymi danymi.")