import sqlite3

conn = sqlite3.connect("flashcards.db")
cursor = conn.cursor()

# Przykładowe zestawy i fiszki
sets = [
    ("Top 100 Phrasal Verbs",),  # Ensure each entry is a tuple
]

cursor.executemany("INSERT INTO sets (name) VALUES (?)", sets)

# Pobierz ID zestawu "Top 100 Phrasal Verbs"
cursor.execute("SELECT id FROM sets WHERE name = ?", sets[0])
set_id = cursor.fetchone()[0]

flashcards = [
("poddawać się", "give up", set_id),
("zdjąć", "take off", set_id),
("opiekować się", "look after", set_id),
("szukać", "look for", set_id),
("nie móc się doczekać", "look forward to", set_id),
("wstać", "get up", set_id),
("kontynuować", "go on", set_id),
("włączyć", "turn on", set_id),
("wyłączyć", "turn off", set_id),
("podnieść", "pick up", set_id),
("odłożyć", "put down", set_id),
("zabraknąć", "run out of", set_id),
("założyć/ustawić", "set up", set_id),
("zmyślić/pogodzić się", "make up", set_id),
("zepsuć się/załamać się", "break down", set_id),
("poruszyć temat/wychowywać", "bring up", set_id),
("odwołać", "call off", set_id),
("kontynuować", "carry on", set_id),
("dowiedzieć się", "find out", set_id),
("dogadywać się", "get along with", set_id),
("wrócić", "get back", set_id),
("dojść do siebie", "get over", set_id),
("poddawać się", "give in", set_id),
("wrócić", "go back", set_id),
("dorastać", "grow up", set_id),
("poczekać", "hold on", set_id),
("kontynuować", "keep on", set_id),
("zawieść", "let down", set_id),
("zbadać", "look into", set_id),
("uważać", "look out", set_id),
("dostrzec/rozpoznać", "make out", set_id),
("umrzeć", "pass away", set_id),
("wybrać", "pick out", set_id),
("odłożyć na później", "put off", set_id),
("założyć (ubranie)", "put on", set_id),
("spotkać/przypadkowo się natknąć", "run into", set_id),
("wyczerpać", "run out", set_id),
("pożegnać", "see off", set_id),
("wyruszyć", "set off", set_id),
("pomylić się", "slip up", set_id),
("wstać", "stand up", set_id),
("być podobnym", "take after", set_id),
("wyjąć", "take out", set_id),
("wyrzucić", "throw away", set_id),
("przymierzyć", "try on", set_id),
("pojawić się", "turn up", set_id),
("odrzucić", "turn down", set_id),
("uważać", "watch out", set_id),
("ćwiczyć/rozwiązać", "work out", set_id),
("zrywać/rozpadać się", "break up", set_id),
("natknąć się", "come across", set_id),
("wpaść na (pomysł)", "come up with", set_id),
("odciąć", "cut off", set_id),
("wypełnić", "fill in", set_id),
("napełnić", "fill up", set_id),
("wejść/wsiąść", "get in", set_id),
("rozdać/ujawnić", "give away", set_id),
("opóźnić/rabować", "hold up", set_id),
("nadążać", "keep up", set_id),
("sprawdzić", "look up", set_id),
("zemdleć/rozdawać", "pass out", set_id),
("zwrócić uwagę", "point out", set_id),
("znosić", "put up with", set_id),
("pojawić się", "show up", set_id),
("zwolnić (tempo)", "slow down", set_id),
("rozwiązać/posegregować", "sort out", set_id),
("trzymać się", "stick to", set_id),
("wyłączyć", "switch off", set_id),
("włączyć", "switch on", set_id),
("cofnąć/zwrócić", "take back", set_id),
("przejąć", "take over", set_id),
("podrzeć", "tear up", set_id),
("przemyśleć", "think over", set_id),
("wypróbować", "try out", set_id),
("odwrócić", "turn around", set_id),
("zużyć", "use up", set_id),
("obudzić", "wake up", set_id),
("rozgrzać", "warm up", set_id),
("pracować nad", "work on", set_id),
("zameldować się", "check in", set_id),
("wymeldować się/sprawdzić", "check out", set_id),
("podrzucić/spadać", "drop off", set_id),
("przejrzeć/przejść przez", "go through", set_id),
("spędzać czas", "hang out", set_id),
("zwolnić (pracownika)", "lay off", set_id),
("opłacać się", "pay off", set_id),
("wskazać", "point at", set_id),
("zjechać na bok", "pull over", set_id),
("uciekać", "run away", set_id),
("odłożyć", "set aside", set_id),
("popisywać się", "show off", set_id),
("wyróżniać się", "stand out", set_id),
("zacząć (hobby)", "take up", set_id),
("odwracać uwagę", "distract", set_id),
("zatkać", "shut up", set_id),
("udać się (powieść się)", "work out", set_id),
("udać się (ktoś idzie)", "show up", set_id),
("wymknąć się", "slip away", set_id),
("przełączać", "switch over", set_id),
("zgodzić się", "go along with", set_id),
("kłócić się", "fall out", set_id),
("zacząć", "set in", set_id),
("odwiesić", "put down", set_id),
("odrzucać", "brush off", set_id),
("bić się", "pick on", set_id),
("zrezygnować", "back out", set_id),
("zawrócić", "turn back", set_id),
("zawracać uwagę na", "focus on", set_id),
("wejść (do budynku)", "come in", set_id),
("wyjść (z budynku)", "go out", set_id),
("przejąć kontrolę", "take charge", set_id),
("wpaść na kogoś", "run across", set_id),
("odpowiadać", "answer back", set_id),
("zwrócić", "hand in", set_id),
("wypić", "drink up", set_id),
("posprzątać", "clean up", set_id),
("odpocząć", "rest up", set_id),
("zwrócić uwagę", "call attention to", set_id),
]

cursor.executemany("INSERT INTO flashcards (word_pl, word_en, set_id) VALUES (?, ?, ?)", flashcards)

conn.commit()
conn.close()

print("Baza danych została zaktualizowana i wypełniona przykładowymi danymi.")