import sqlite3

conn = sqlite3.connect("flashcards.db")
cursor = conn.cursor()

# Przykładowy zestaw i fiszki
set_name = "Top 100 sentences"

cursor.execute("INSERT INTO sets (name) VALUES (?)", (set_name,))

# Pobierz ID zestawu "Top 100 Business phrases"
cursor.execute("SELECT id FROM sets WHERE name = ?", (set_name,))
set_id = cursor.fetchone()[0]

flashcards = [
("Cześć!", "Hello!"),
("Jak się masz?", "How are you?"),
("Dzień dobry", "Good morning"),
("Dobry wieczór", "Good evening"),
("Dobranoc", "Good night"),
("Do widzenia", "Goodbye"),
("Proszę", "Please"),
("Dziękuję", "Thank you"),
("Przepraszam", "I'm sorry"),
("Nie ma za co", "You're welcome"),
("Tak", "Yes"),
("Nie", "No"),
("Może", "Maybe"),
("Jak masz na imię?", "What's your name?"),
("Nazywam się Anna", "My name is Anna"),
("Skąd jesteś?", "Where are you from?"),
("Jestem z Polski", "I'm from Poland"),
("Ile masz lat?", "How old are you?"),
("Mam dwadzieścia pięć lat", "I'm twenty-five years old"),
("Czym się zajmujesz?", "What do you do?"),
("Jestem studentem", "I'm a student"),
("Gdzie mieszkasz?", "Where do you live?"),
("Mieszkam w Warszawie", "I live in Warsaw"),
("Co robisz w wolnym czasie?", "What do you do in your free time?"),
("Lubię czytać książki", "I like reading books"),
("Jaki jest dzisiaj dzień?", "What day is it today?"),
("Dzisiaj jest czwartek", "Today is Thursday"),
("Jaka jest pogoda?", "How's the weather?"),
("Jest słonecznie", "It's sunny"),
("Czy pada deszcz?", "Is it raining?"),
("Jestem głodny", "I'm hungry"),
("Chcę coś zjeść", "I want to eat something"),
("Gdzie jest toaleta?", "Where is the bathroom?"),
("Ile to kosztuje?", "How much does it cost?"),
("Poproszę rachunek", "The bill, please"),
("Czy mogę zapłacić kartą?", "Can I pay by card?"),
("Pomocy!", "Help!"),
("Zadzwoń na pogotowie!", "Call an ambulance!"),
("Jestem zmęczony", "I'm tired"),
("Muszę iść spać", "I have to go to sleep"),
("Obudź mnie o siódmej", "Wake me up at seven"),
("Spotkamy się później", "We will meet later"),
("Do zobaczenia jutro", "See you tomorrow"),
("Miło cię poznać", "Nice to meet you"),
("Mi też miło", "Nice to meet you too"),
("Co polecasz?", "What do you recommend?"),
("Lubię kawę", "I like coffee"),
("Proszę kawę z mlekiem", "Coffee with milk, please"),
("Czy masz plan na weekend?", "Do you have plans for the weekend?"),
("Tak, jadę nad morze", "Yes, I'm going to the seaside"),
("Nie mam pojęcia", "I have no idea"),
("Chciałbym zarezerwować pokój", "I'd like to book a room"),
("O której godzinie?", "At what time?"),
("O ósmej rano", "At eight in the morning"),
("Czy możesz powtórzyć?", "Can you repeat that?"),
("Mówię tylko trochę po angielsku", "I speak only a little English"),
("Rozumiem", "I understand"),
("Nie rozumiem", "I don't understand"),
("Proszę mówić wolniej", "Please speak more slowly"),
("Jak to się nazywa po angielsku?", "What is this called in English?"),
("Gdzie mogę kupić bilet?", "Where can I buy a ticket?"),
("Jadę autobusem", "I'm taking the bus"),
("Gdzie jest stacja kolejowa?", "Where is the train station?"),
("Kiedy odjeżdża pociąg?", "When does the train leave?"),
("Czy to miejsce jest wolne?", "Is this seat taken?"),
("Chciałbym zamówić taksówkę", "I'd like to order a taxi"),
("Jadę na lotnisko", "I'm going to the airport"),
("Mój lot jest opóźniony", "My flight is delayed"),
("Gdzie jest wyjście?", "Where is the exit?"),
("Czy masz mapę miasta?", "Do you have a city map?"),
("Proszę pokazać na mapie", "Please show me on the map"),
("Ile przystanków?", "How many stops are there?"),
("To daleko stąd?", "Is it far from here?"),
("Czy mogę tu parkować?", "Can I park here?"),
("Mam rezerwację na nazwisko Kowalski", "I have a reservation under the name Kowalski"),
("Czy serwujecie wegetariańskie dania?", "Do you serve vegetarian dishes?"),
("Jestem alergikiem", "I have allergies"),
("Czy masz wolny pokój?", "Do you have a vacant room?"),
("Poproszę o dodatkowy ręcznik", "Please bring an extra towel"),
("Gdzie jest winda?", "Where is the elevator?"),
("Nie działa klimatyzacja", "The air conditioning is not working"),
("Czy mogę dostać więcej mydła?", "Can I have more soap?"),
("Proszę o budzenie telefoniczne", "Please call me for wake-up service"),
("Gdzie jest najbliższy bankomat?", "Where is the nearest ATM?"),
("Jaki jest numer alarmowy?", "What is the emergency number?"),
("Potrzebuję lekarza", "I need a doctor"),
("Do you accept Euros?", "Czy akceptujecie euro?"),
("To jest bardzo drogie", "This is very expensive"),
("Szukam apteki", "I'm looking for a pharmacy"),
("Jedź prosto", "Go straight ahead"),
("Skręć w lewo", "Turn left"),
("Skręć w prawo", "Turn right"),
("Przepraszam za spóźnienie", "Sorry for being late"),
("Gratulacje!", "Congratulations!"),
("Wszystkiego najlepszego!", "Happy birthday!"),
("Sto lat!", "May you live a hundred years!"),
("Powodzenia!", "Good luck!"),
("Smacznego!", "Enjoy your meal!"),
("Na zdrowie!", "Cheers!"),
("Udanego dnia!", "Have a nice day!"),
("Miłego weekendu!", "Have a nice weekend!"),
("Do zobaczenia wkrótce", "See you soon"),
("Miłej podróży", "Have a pleasant trip"),
("Co to znaczy?", "What does that mean?"),
("Mogę zrobić zdjęcie?", "Can I take a picture?"),
("To jest moje pierwsze raz tu", "It's my first time here"),
("Wszystko w porządku?", "Is everything okay?"),
("Jestem na diecie", "I'm on a diet"),
("Nie palę", "I don't smoke"),
("Palić można tylko na zewnątrz", "Smoking is only allowed outside"),
("Czy masz wolne miejsce?", "Do you have any vacancy?"),
("Potrzebuję pomocy", "I need help"),
("Czy mogę to przymierzyć?", "Can I try this on?"),
("Jak dojść do centrum?", "How do I get to the city center?"),
("Czy tutaj są darmowe Wi-Fi?", "Is there free Wi-Fi here?"),
("Jaki jest kod do Wi-Fi?", "What's the Wi-Fi password?"),
("Mam pytanie", "I have a question"),
("Proszę o informacje", "Please give me information"),
("Czy to jest możliwe?", "Is it possible?"),
("Muszę to przemyśleć", "I need to think about it"),
("Jestem wegetarianinem", "I'm a vegetarian"),
("Nie jem mięsa", "I don't eat meat"),
("Czy to dużo waży?", "Is it heavy?"),
("Gdzie mogę zostawić bagaż?", "Where can I leave my luggage?"),
("Czy to jest bezpieczne?", "Is it safe?"),
("Zgubiłem paszport", "I lost my passport"),
("Muszę wymienić pieniądze", "I need to exchange money"),
("Która godzina?", "What time is it?"),
("Mam spotkanie o trzynastej", "I have a meeting at one o'clock"),
("Czy możemy zacząć?", "Can we start?"),
("Proszę mówić głośniej", "Please speak louder"),
("To jest pilne", "This is urgent"),
("Dziękuję za pomoc", "Thank you for your help"),
("Do usłyszenia!", "Talk to you later!"),
("Miłego dnia!", "Have a great day!"),
("Powiedz mi prawdę", "Tell me the truth"),
("Nie spiesz się", "Take your time"),
("Zrelaksuj się", "Relax"),
("Jestem szczęśliwy", "I'm happy"),
("Jestem smutny", "I'm sad"),
("Jestem zaskoczony", "I'm surprised"),
("Bardzo mi się podoba", "I like it very much"),
("Nie podoba mi się to", "I don't like it"),
("To brzmi dobrze", "That sounds good"),
("To nie ma sensu", "It doesn't make sense"),
("Przyjdź w porę", "Be on time"),
("Zadzwoń do mnie później", "Call me later"),
("Pomóż mi proszę", "Please help me"),
("Gdzie mogę znaleźć taksówkę?", "Where can I find a taxi?"),
("Ile czasu to zajmie?", "How long will it take?"),
("Co się stało?", "What happened?"),
("Kiedy się spotkamy?", "When will we meet?"),
("Czy masz chwilę?", "Do you have a moment?"),
("Jestem spóźniony", "I'm running late"),
("Zamknij drzwi", "Close the door"),
("Otwórz okno", "Open the window"),
("Powiedz to jeszcze raz", "Say it again"),
("Jestem zajęty", "I'm busy"),
("To jest łatwe", "This is easy"),
("To jest trudne", "This is difficult"),
("Znam to miejsce", "I know this place"),
("Nie znam tego", "I don't know this"),
("Bądź ostrożny", "Be careful"),
("Trzymaj się", "Take care"),
("Całkowicie się z tobą zgadzam", "I completely agree with you"),
("Nie zgadzam się", "I don't agree"),
("Może być", "It can be"),
("Jestem gotowy", "I'm ready"),
("To jest ważne", "This is important"),
("Nie martw się", "Don't worry"),
("Uda ci się", "You can do it"),
("Zadzwonię do ciebie jutro", "I will call you tomorrow"),
("Muszę iść", "I have to go"),
("Wrócę później", "I'll be back later"),
("Co myślisz?", "What do you think?"),
("Mam nadzieję, że tak", "I hope so"),
("Na pewno", "Definitely"),
("To jest zabawne", "This is funny"),
("Nie jest śmieszne", "It's not funny"),
("Jestem zdenerwowany", "I'm nervous"),
("Spokojnie", "Calm down"),
("Jestem zdumiony", "I'm amazed"),
("To jest niesamowite", "This is amazing"),
("To jest okropne", "This is horrible"),
("Nie uwierzę w to", "I can't believe it"),
("Naprawdę?", "Really?"),
("To jest prawda", "That's true"),
("Nie to nieprawda", "No, that's not true"),
("Możesz to zrobić", "You can do it"),
("To jest plan", "That's the plan"),
("Jest już późno", "It's already late"),
("Czy to wszystko?", "Is that all?"),
("Tak, to wszystko", "Yes, that's all"),
("Nie, jest jeszcze więcej", "No, there's more"),
("Kończmy", "Let's finish"),
("Zacznijmy od nowa", "Let's start over"),
("Powodzenia!", "Good luck!"),
("To byłoby wszystko", "That would be all"),
("Nie mogę się doczekać", "I can't wait"),
("Do zobaczenia!", "See you!"),
("Dbaj o siebie", "Take care of yourself"),
("Na razie!", "Bye for now!"),
("Do następnego razu", "Until next time"),
("Miłego wieczoru!", "Have a nice evening!"),
("Smacznego obiadu!", "Enjoy your lunch!"),
("Smacznej kolacji!", "Enjoy your dinner!"),
("Nie przeszkadzaj mi", "Don't disturb me"),
("Proszę się nie denerwować", "Please don't get upset"),
("Czy wszystko gra?", "Is everything okay?"),
("Muszę to zakończyć", "I have to finish this"),
("To jest niesamowite doświadczenie", "This is an amazing experience"),
("Dziękuję za uwagę", "Thank you for your attention"),
("To wszystko na dzisiaj", "That's all for today"),
("Życzę miłego dnia", "I wish you a nice day"),
("Życzę miłego wieczoru", "I wish you a pleasant evening"),
("Życzę dobrej nocy", "I wish you a good night"),
("Nie zapomnij", "Don't forget"),
("Zobaczymy się później", "We'll see each other later"),
("To jest naprawdę ciekawe", "This is really interesting"),
("Czy byłeś kiedyś tutaj?", "Have you ever been here?"),
("To jest twoja kolej", "It's your turn"),
("Dziękuję bardzo", "Thank you very much"),
("Nie dziękuj", "Don't mention it"),
("Zgadza się", "That's right"),
("To nieprawda", "That's not true"),
("To jest doskonałe", "It's perfect"),
("To wymaga poprawy", "It needs improvement"),
("Nie mam czasu", "I don't have time"),
("Muszę się pośpieszyć", "I have to hurry"),
("Stop!", "Stop!"),
("Proszę stać tutaj", "Please stand here"),
("Możesz usiąść", "You may sit down"),
("Zapraszam", "After you"),
("Miło cię widzieć", "It's nice to see you"),
("Oczywiście", "Of course"),
("Naturalnie", "Naturally"),
("Bez wątpienia", "Without a doubt"),
("To zależy", "It depends"),
("Nie szkodzi", "Never mind"),
("Teraz nie mogę", "I can't right now"),
("Może później", "Maybe later"),
("Zaraz wracam", "I'll be right back"),
("Przyjdź jutro", "Come tomorrow"),
("Czekam na ciebie", "I'm waiting for you"),
("Jestem tutaj", "I'm here"),
("Odezwij się", "Get in touch"),
("Baw się dobrze!", "Have fun!"),
("Miło mi było z tobą porozmawiać", "It was nice talking to you"),
("Do usłyszenia wkrótce", "Talk to you soon"),
("Nieźle ci idzie", "You're doing well"),
("Świetna robota!", "Great job!"),
("Dobra robota!", "Well done!"),
("Możesz mi pomóc?", "Can you help me?"),
("Tak, oczywiście", "Yes, of course"),
("Nie mam pojęcia", "I have no idea"),
("Zadzwoń po taksówkę", "Call a taxi"),
("Czy mogę tu usiąść?", "May I sit here?"),
("Proszę mówić powoli", "Please speak slowly"),
("To wszystko, dziękuję", "That's all, thank you"),
("Do następnego spotkania", "Until our next meeting"),
("Na zdrowie!", "Bless you!"),
("Skręć w prawo na światłach", "Turn right at the lights"),
("Jedź ostrożnie", "Drive carefully"),
("Mam rezerwację", "I have a reservation"),
("Potrzebuję informacji", "I need information"),
("Czy tu jest cisza?", "Is it quiet here?"),
("To było pyszne", "That was delicious"),
("Chciałbym deser", "I'd like dessert"),
("To jest doskonałe", "This is excellent"),
("To jest zbyt drogie", "This is too expensive"),
("Masz rację", "You are right"),
("Nie masz racji", "You are wrong"),
("Co zamówiłeś?", "What did you order?"),
("Poproszę o rachunek", "Check, please"),
("Muszę iść do pracy", "I have to go to work"),
("Przygotuj się", "Get ready"),
("Nie spiesz się", "Don't rush"),
("Zrelaksuj się", "Take it easy"),
("Do zobaczenia na spotkaniu", "See you at the meeting"),
("Chciałbym porozmawiać", "I would like to talk"),
("To jest ważne", "This is important"),
("Jestem wolny o ósmej", "I'm free at eight"),
("Czy to jest bezpieczne?", "Is it safe?"),
("Jestem zadowolony", "I'm pleased"),
("Jestem zawiedziony", "I'm disappointed"),
]

cursor.executemany("INSERT INTO flashcards (word_pl, word_en, set_id) VALUES (?, ?, ?)", [(word_pl, word_en, set_id) for word_pl, word_en in flashcards])

conn.commit()
conn.close()

print("Baza danych została zaktualizowana i wypełniona przykładowymi danymi")